// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1YR4QqTCueG6iDLZUl6YxOAr_7lARjIs',
    appId: '1:387181885801:web:6f603ed4e0ee82027865f8',
    messagingSenderId: '387181885801',
    projectId: 'scu-course-planner-5df63',
    authDomain: 'scu-course-planner-5df63.firebaseapp.com',
    storageBucket: 'scu-course-planner-5df63.firebasestorage.app',
    measurementId: 'G-KDPK45YJCT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgoiPjGDrZ9iTdPelucVRkFbl8myHSp0M',
    appId: '1:387181885801:android:a427dfe50e89eea57865f8',
    messagingSenderId: '387181885801',
    projectId: 'scu-course-planner-5df63',
    storageBucket: 'scu-course-planner-5df63.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCTqFZPvNwmEIjAgtD1b4ac9dNFOBQENQ',
    appId: '1:387181885801:ios:f20ca46c755172857865f8',
    messagingSenderId: '387181885801',
    projectId: 'scu-course-planner-5df63',
    storageBucket: 'scu-course-planner-5df63.firebasestorage.app',
    iosClientId: '387181885801-63c8brv0j6vvsv9haqfgpe421ep1jpss.apps.googleusercontent.com',
    iosBundleId: 'com.example.focusflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCTqFZPvNwmEIjAgtD1b4ac9dNFOBQENQ',
    appId: '1:387181885801:ios:f20ca46c755172857865f8',
    messagingSenderId: '387181885801',
    projectId: 'scu-course-planner-5df63',
    storageBucket: 'scu-course-planner-5df63.firebasestorage.app',
    iosClientId: '387181885801-63c8brv0j6vvsv9haqfgpe421ep1jpss.apps.googleusercontent.com',
    iosBundleId: 'com.example.focusflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3vmNPSIJVpREaqlFjRo5pmbHq2cPjpx4',
    appId: '1:387181885801:web:fbdbad575c896c377865f8',
    messagingSenderId: '387181885801',
    projectId: 'scu-course-planner-5df63',
    authDomain: 'scu-course-planner-5df63.firebaseapp.com',
    storageBucket: 'scu-course-planner-5df63.firebasestorage.app',
    measurementId: 'G-KNWX8V2JY6',
  );
}
